// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using React_AspNetCore.Server.EFCore;

#nullable disable

namespace React_AspNetCore.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("React_AspNetCore.Server.Models.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("ModifierId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("React_AspNetCore.Server.Models.TodoHeaders.TodoHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("ModifierId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.ToTable("TodoHeaders", (string)null);
                });

            modelBuilder.Entity("React_AspNetCore.Server.Models.TodoItems.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid?>("ModifierId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("TodoHeaderId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("TodoHeaderId");

                    b.ToTable("TodoItems", (string)null);
                });

            modelBuilder.Entity("React_AspNetCore.Server.Models.TodoItems.TodoItem", b =>
                {
                    b.HasOne("React_AspNetCore.Server.Models.TodoHeaders.TodoHeader", "TodoHeader")
                        .WithMany("TodoItems")
                        .HasForeignKey("TodoHeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TodoHeader");
                });

            modelBuilder.Entity("React_AspNetCore.Server.Models.TodoHeaders.TodoHeader", b =>
                {
                    b.Navigation("TodoItems");
                });
#pragma warning restore 612, 618
        }
    }
}
